// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKTrqmJVqEoD5y1olE7IrBe794cMk3IXE',
    appId: '1:1034519381902:web:4e646375a8fe24a8ecc6df',
    messagingSenderId: '1034519381902',
    projectId: 'bet-app-e520a',
    authDomain: 'bet-app-e520a.firebaseapp.com',
    storageBucket: 'bet-app-e520a.appspot.com',
    measurementId: 'G-SL6PELXYYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZbhxIH_9XCagxWlFze4_0EOS1Nca96UY',
    appId: '1:1034519381902:android:240e1dd8a5f9326becc6df',
    messagingSenderId: '1034519381902',
    projectId: 'bet-app-e520a',
    storageBucket: 'bet-app-e520a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQT5vZOlINXVGnzUqudeame3Z69f8txNA',
    appId: '1:1034519381902:ios:cc630790b47f42a3ecc6df',
    messagingSenderId: '1034519381902',
    projectId: 'bet-app-e520a',
    storageBucket: 'bet-app-e520a.appspot.com',
    iosClientId: '1034519381902-lhqkt5r6ktvaj68d3mi3gdolatn6bd2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQT5vZOlINXVGnzUqudeame3Z69f8txNA',
    appId: '1:1034519381902:ios:ecd6fd6f9b8b5aa1ecc6df',
    messagingSenderId: '1034519381902',
    projectId: 'bet-app-e520a',
    storageBucket: 'bet-app-e520a.appspot.com',
    iosClientId: '1034519381902-uhsakatsjqj2bk6ts70l9cd5m25ftuth.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
