// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY']!,
    appId: '1:1034519381902:web:4e646375a8fe24a8ecc6df',
    messagingSenderId: '1034519381902',
    projectId: 'bet-app-e520a',
    authDomain: 'bet-app-e520a.firebaseapp.com',
    storageBucket: 'bet-app-e520a.appspot.com',
    measurementId: 'G-SL6PELXYYC',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY']!,
    appId: '1:1034519381902:android:240e1dd8a5f9326becc6df',
    messagingSenderId: '1034519381902',
    projectId: 'bet-app-e520a',
    storageBucket: 'bet-app-e520a.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY']!,
    appId: '1:1034519381902:ios:cc630790b47f42a3ecc6df',
    messagingSenderId: '1034519381902',
    projectId: 'bet-app-e520a',
    storageBucket: 'bet-app-e520a.appspot.com',
    iosClientId: '1034519381902-lhqkt5r6ktvaj68d3mi3gdolatn6bd2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
