name: Linter

on: [push, pull_request]

jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Run the superlinter
        uses: github/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: master
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_DART: true
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}